### ISSUE TITLE
Display verified team names

### ISSUE THREAD

**Issue by JJscott** [bluefantail/blujm#20]
Two parts:

Part one, allow admin users to mark teams as verified through team interface.

Part two, display all verified teams below the signups form in the signups section in a pretty fashion.

**Comment by bluefantail** [comment]
team-display branch now has all teams displaying underneath signups. Just needs team verification adding to it.

**Comment by JJscott** [comment]
Confirmed on beta. Waiting for push to prod, but will close in mean time
