### ISSUE TITLE
Signups Open message

### ISSUE THREAD

**Issue by bluefantail** [bluefantail/blujm#3]
Message to show at the top of webpage when signups are open

**Comment by bluefantail** [comment]
Have pushed to signups branch for review @bagedevimo @JJscott @benos-9k de16b6c956b18a76464d63b74daa394b7627a565

**Comment by bluefantail** [comment]
Needs to be bigger

**Comment by bluefantail** [comment]
This big enough @JJscott ?

**Comment by JJscott** [comment]
@bluefantail I've checked beta.bujm.co.nz would be nice if it were say 200-300% bigger?

**Comment by JJscott** [comment]
Issue closed. Sufficiently big. (That's what she said)
