### ISSUE TITLE
Error message. Email in use.

### ISSUE THREAD

**Issue by JJscott** [bluefantail/blujm#5]
Error message for email in use doe not specify which email. Should either explicitly state the email, or visually indicate which one needs to be changed.

![image](https://cloud.githubusercontent.com/assets/5070852/13687126/6338aa4e-e77e-11e5-8556-99fd98faf9b5.png)

**Comment by JJscott** [comment]
Note, the Yellow box in image is a google chrome highlighting feature.

**Comment by bagedevimo** [comment]
Fixed, confirm fix and close when you're ready Josh.
